version: 1
update_configs:
- package_manager: dotnet:nuget
  directory: /
  update_schedule: live
  target_branch: master
  default_labels:
  - dependencies
  allowed_updates:
  - match:
      update_type: all
      dependency_type: direct
