name: "Rebase Required"

on:
  push:
  pull_request_target:
    types: [synchronize]

jobs:
  label-rebase-required:
    name: Check Rebase Required
    runs-on: ubuntu-latest
    steps:
      - name: Check for merge conflicts
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "rebase needed :construction:"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: This pull request has merge conflicts that must be resolved before it can be merged.
